services:
  - type: web
    name: movie-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Xmx256m
    healthCheckPath: /health
    autoDeploy: true